wandb_version: 1

batch_size:
  value: 16
dev:
  value: data/dev_unbiased.jsonl
epochs:
  value: 10
lr:
  value: 0.0003198121655306951
max_length:
  value: 64
model_name:
  value: distilbert-base-uncased
out_dir:
  value: out/sweep_run
train:
  value: data/train_unbiased.jsonl
