_wandb:
    value:
        cli_version: 0.23.0
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
            "3":
                - 16
            "4": 3.13.7
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": linux-x86_64
batch_size:
    value: 8
dev:
    value: data/dev.jsonl
device:
    value: cuda
epochs:
    value: 3
lr:
    value: 5e-05
max_length:
    value: 256
model_name:
    value: distilbert-base-uncased
out_dir:
    value: out
train:
    value: data/train.jsonl
