wandb_version: 1

batch_size:
  value: 32
dev:
  value: data/dev_unbiased.jsonl
epochs:
  value: 10
lr:
  value: 0.0002034701147974926
max_length:
  value: 128
model_name:
  value: distilbert-base-uncased
out_dir:
  value: out/sweep_run
train:
  value: data/train_unbiased.jsonl
